# conda-build environment for heavy fixtures
name: jupyter-lite-fixtures

channels:
  - conda-forge/label/jupyterlab_rc
  - conda-forge

dependencies:
  # TODO: sync/check these against... something
  - boa
  - conda-build
  - doit
  - jupyterlab >=3.1.0rc2,<4
  - mamba
  - nodejs >=14,<15
  - pip
  - python >=3.9,<3.10
