name: jupyterlite-docs
# this is a conda/mamba environment for building the JupyterLite documentation

channels:
  - conda-forge
  - nodefaults

dependencies:
  # the chunk below gets copied to ../.binder/environment.yml
  ### DOCS ENV ###
  # runtimes
  - nodejs >=14,<15
  - python >=3.8,<3.9
  # build
  - doit >=0.33,<0.34
  - flit >=3.1
  - pip
  - wheel
  - jsonschema >=3
  - yarn <2
  # cli
  - wheel
  # docs
  - myst-nb
  - pydata-sphinx-theme
  - sphinx
  - sphinx-autodoc-typehints
  - sphinx-jsonschema
  - sphinxext-rediraffe
  # check
  - pytest-check-links
  # test
  - ansi2html
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-xdist
  ### DOCS ENV ###
